# Generated by Django 2.1.1 on 2018-12-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='subjectId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='back.Subject'),
            preserve_default=False,
        ),
    ]
